### ISSUE TITLE
ASAN

### ISSUE THREAD

**Issue by freedom1b2830** [astrand/xclip#144]
xclip-git r173.b372f73-3

https://aur.archlinux.org/packages/xclip-git + ASAN
cmd:
```sh
xclip -selection
```
output
```
xclip: -selection: No such file or directory

=================================================================
==545945==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x5637069098a9 in __interceptor_malloc (/usr/bin/xclip+0x10c8a9) (BuildId: f7c11fa0b8ff521cc9f4193a070dba6b1ee26a0f)
    #1 0x5637069514c9 in xcmalloc /usr/src/debug/xclip-git/xclip/xclib.c:71:11
    #2 0x5637069542bd in doIn /usr/src/debug/xclip-git/xclip/xclip.c:371:15
    #3 0x56370695393f in main /usr/src/debug/xclip-git/xclip/xclip.c:972:14
    #4 0x7f91d1b0fccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)

SUMMARY: AddressSanitizer: 16 byte(s) leaked in 1 allocation(s).
```

**Comment by quartzjer** [comment]
Hi @freedom1b2830! Would you be interested in making a PR for this?
